services:
  - type: web
    name: huntwithOdin-ad-creator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    plan: free
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: BUFFER_ACCESS_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.0"
